# Generated by Django 2.0.13 on 2021-01-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devtool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='이름', max_length=100)),
                ('kind', models.CharField(help_text='종류', max_length=100)),
                ('desc', models.TextField(blank=True, help_text='개발툴 설명')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='아이디어명', max_length=100)),
                ('image', models.ImageField(help_text='대표 사진', upload_to='idea_main_image')),
                ('content', models.TextField(blank=True, help_text='아이디어 설명')),
                ('interest', models.IntegerField(default=0, help_text='아이디어 관심도')),
                ('devtool', models.CharField(help_text='예상 개발툴', max_length=100)),
            ],
        ),
    ]
