# Generated by Django 2.0.13 on 2021-01-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='devtool',
            field=models.CharField(choices=[('django', 'django'), ('Pytorch', 'Pytorch'), ('Node.js', 'Node.js'), ('JavaScript', 'JavaScript'), ('Spring', 'Spring')], help_text='예상 개발툴', max_length=100),
        ),
    ]
