# Generated by Django 2.0.13 on 2021-01-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210120_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='devtool',
            field=models.CharField(choices=[('JavaScript', 'JavaScript'), ('Node.js', 'Node.js'), ('django', 'django'), ('Pytorch', 'Pytorch'), ('Spring', 'Spring')], help_text='예상 개발툴', max_length=100),
        ),
    ]
